grab/grab-bazel-common

tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/parser/xml/DeclareStyleableParser.kt, tools/db-compiler-lite/src/test/java/com/grab/databinding/stub/rclass/parser/ResToRStyleableValueParserTest.kt
To handle parent name with dot.
XML:
```
<declare-styleable name="BaseTheme.AppTheme">
<attr name="CheckboxDefaultStyle" format="reference"/>
</declare-styleable>
```
error message:
```
r-classes/com/albertjanuar/android/arjuna/R.java:7659: error: unexpected token: .
public static int BaseTheme.AppTheme_CheckboxDefaultStyle = 0;
```
=> Replace styleable parent name separator from dot to underscore

tools/auto-service/BUILD.bazel, tools/binding-adapter-bridge/BUILD.bazel, tools/databinding/databinding.bzl, tools/databinding/utils.bzl, tools/test-suite-generator/BUILD.bazel, tools/test/jvm/BUILD.bazel, tools/test/test.bzl
Applies buildifier on whole project. We need validation in workflows as part of PR checks and that can be done in a different PR.
=> Apply `buildifier` on whole project

WORKSPACE, tools/test/android/BUILD.bazel, tools/test/android/src/main/java/com/grab/test/TestActivity.kt, tools/test/android/src/test/java/com/grab/test/SimpleActivityTest.kt, tools/test/runtime_resources.bzl, tools/test/test.bzl
During test execution, the target's dependencies' resources is only made available during compile time but not runtime. This causes references to external resources like the material library (via `com.google.android.material.R`) to end up with a `NoClassDefFoundError`.
This change will add a rule to `grab_android_local_test` that will get the transitive compile resources jar to be available on runtime as a dependency.
=> Expose test's compile time resources on runtime

tools/databinding/databinding.bzl
Generated stub R classes for `databinding` which contains all zeros was being loaded onto runtime classpath during unit tests which causes all the resources to not be accurate.
This change is to ensure that the generated stub R classes is first compiled with `neverlink = 1` and added to the `kt_jvm_library` as a dependency so that they are only used for compiling.
=> Stub R classes loaded into runtime during tests

tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/generator/ResToRClassGenerator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/parser/ResToRParser.kt, tools/db-compiler-lite/src/test/java/com/grab/databinding/stub/rclass/parser/ResToRStyleableValueParserTest.kt
It is not uncommon to have attrs defined on a custom view that are in the Android XML NS, e.g.
```xml
<resources>
<declare-styleable name="IconToggleButton">
<attr name="android:drawableTint" format="reference" />
<attr name="icon" format="reference" />
<attr name="colorTheme" format="enum">
<enum name="DEFAULT" value="0" />
<enum name="DARK" value="1" />
<enum name="CREAM" value="2" />
</attr>
<attr name="themeCream" format="boolean" />
<attr name="themeDark" format="boolean" />
</declare-styleable>
</resources>
```
`android:drawableTint` here lets users set familiar attributes on custom views.
In order to support this, Gradle converts it to, in R.txt:
```
int styleable IconToggleButton_android_drawableTint 5
```
This suggests that the right way to account for it is to replace invalid …
=> Accept names with colon for XML namespace

tools/binding-adapter-bridge/src/main/java/com/grab/pax/binding/processor/BindingAdapterProcessor.kt, tools/binding-adapter-bridge/src/test/java/com/grab/pax/binding/processor/BindingAdapterProcessorTest.kt
Support cases where `@BindingAdapter` is statically declared in a class that uses generic in its type params. This change fixes code generation to not generate generic information in generated code for those classes since static access is invalid in Java/Kotlin.
Fixes #16
=> Handle cases of using class with generics for `@BindingAdapter` in binding-adapter-bridge

README.md, tools/res_value/res_value.bzl
Previously `res_value` generates a dedicated `android_library` target just for hosting generated resource values. This change instead adds the generated xml as the output of `res_value` so that it can be used in `resource_files` directly.
=> Avoid dedicated `android_library` target for `res_value` and instead compile resources directly

tools/databinding/databinding.bzl, tools/res_value/res_value.bzl
Without this, using two `kt_db_android_library` targets in the same package fails with:
```
File "/mypath/app/BUILD.bazel", line 251, column 22, in <toplevel>
kt_db_android_library(
File "/private/var/tmp/_bazel_p/c1a9d93c5d307e720ae1d0573bce325b/external/grab_bazel_common/tools/databinding/databinding.bzl", line 89, column 24, in kt_db_android_library
native.java_library(
Error in java_library: java_library rule 'r-classes' in package 'app' conflicts with existing java_library rule, defined at /mypath/app/BUILD.bazel:230:22
```
=> Prefix R classes with name to avoid conflicts

tools/databinding/databinding.bzl
The binding adapter sources generation `genrule` unnecessarily extracts whole sources jar from Kotlin target and then filters all `_Binding_Adapter_Stub.java` files. While that is fine, on large Kotlin targets we are spending time on extracting all the files and then deleting and packaging again. Instead of that, we can directly use `unzip` API to selectively extract the files we need and generate the srcjar.
=> Optimize binding adapter `srcjar` preparation by avoiding extracting whole source jars

README.md, src/main/proto/BUILD.bazel, tools/databinding/databinding_stubs.bzl, tools/db-compiler-lite/BUILD, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/BindingStubCommand.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/BindingsStubComponent.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/binding/generator/BindingClassGenerator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/binding/parser/LayoutBindingsParser.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/binding/store/BindingClassJsonParser.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/binding/store/LayoutTypeStore.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/brclass/BrClassGenerator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/common/Constants.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/common/Generator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/common/SrcJarPackager.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/main.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/ResToRClassModule.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/generator/RClassGenerator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/generator/ResToRClassGenerator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/parser/RTxtParser.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/parser/ResToRParser.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/util/Utils.kt, tools/db-compiler-lite/src/test/java/com/grab/databinding/stub/binding/generator/DefaultBindingClassGeneratorTest.kt, tools/db-compiler-lite/src/test/java/com/grab/databinding/stub/brclass/DefaultBrClassGeneratorTest.kt
Continuing from https://github.com/grab/grab-bazel-common/pull/37, this PR implements worker/multiplex-worker support for the stub generator actions. 
1. On the compiler side, cleaned up to write directly to paths provided from bazel
2. Since single process will be shared in multiplexing mode, `@Singleton` scope for the stub component did not feel right, hence introduced a new scope `@AaptScope`. Later we can rename the compiler to `MiniAapt` since it is doing more than databinding stub generation.
Fixes #5
=> Implement multiplexing worker support for databinding stub generator

patches/bazel/README.md, tools/databinding/databinding_stubs.bzl
- Update `android_tools` jar as per latest patches
- Minor optimization in stub generation to not process `class-info.zip`s when the module has no layouts.
=> Update android tools

tools/build_config/build_config.bzl, tools/databinding/databinding.bzl, tools/java/java_library_no_header.bzl
- Even though we are generating header like `R.java` with stub values, by default `java_library` compiles it again twice, one in normal and in header mode. Header compilation is wasteful here since `r-classes` target is on the critical path in the databinding module. This change implements idea from https://github.com/bazelbuild/bazel/issues/12837#issuecomment-766155870 which provides a transition to disable headers on a per target basis. 
-  This is needed until https://github.com/grab/grab-bazel-common/issues/35 is implemented.
- In build config generate `BuildConfig.kt` directly instead of generating a `srcjar` which has to be unpacked to compile.
=> Disable header compilation for r-classes

tools/databinding/databinding.bzl
Identified few compilation issues with Linux hence disabling non header target. Will prioritize #35 instead.
=> Revert: Disable header compilation for r-classes

tools/test/test.bzl
#34 Improves on the test package detection by allowing a list of test packages. This detection seems to not account to situations where packages are named `com.example.test` and `com.example.testing`. This results to only `com.example.test` getting created into `TestPackageName` class.
This PR fixes this problem by ensuring that the subpackage checks are inclusive of the period `.` in the package name
=> Fix test package detection

tools/test/test.bzl
Test files are currently assumed to be ending with either `Test` or `Tests`. 
Since we already have `AllTests.kt` as a test suite to detect all the files that has test annotation, this restriction can be removed so that there is no assumption on how the `.kt` file is named
=> Remove restriction to test files naming

tools/test/test.bzl
Test files without proper package (e.g. `src/test/java/FooTest.kt`) are currently being ignored. This change is to add in a validation for a hard failure in the event where package-less test files are detected.
=> Fail test analysis if there are test files with no packages

tools/test-suite/src/main/java/com/grab/test/TestSuiteBuilder.kt
The TestSuiteBuilder is currently only detecting `@Test` annotation on methods. 
It is also possible to be extending the `junit.framework.TestCase` class for test to be executed without the `@Test` annotation.
=> Update TestSuite detection to detect junit.framework.Test interface

tools/test/test.bzl
Current source set root path for tests are hard coded to either `src/test/java` or `src/test/kotlin`. This PR enables this source sets to be configurable for `grab_android_local_test` and `grab_kt_jvm_test` where `src_sets` arg (that defaults back to `src/test/java` or `src/test/kotlin`) can be passed in to be use for test execution and detection.
This change will also make the `srcs` arg as an optional argument and in the event where no srcs were given, it will be searched for via `glob` with the `src_sets` as it's pattern
=> Allow configurable source sets for tests

tools/test/test.bzl
Changing the implementation in #48 to use additional source sets instead. This will be used together with the current default source sets (i.e. `src/test/java` and `src/test/kotlin`) to detect the packages that will be used to run tests
=> Change test src sets to additional src sets

tools/android/BUILD.bazel, tools/databinding/databinding.bzl, tools/databinding/databinding_stubs.bzl, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/binding/generator/BindingClassGenerator.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/binding/generator/DatabiningComponent.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/common/Constants.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/main.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/mapper/GenerateDatabindingMapper.kt, tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/mapper/MapperComponent.kt, tools/db-compiler-lite/src/test/java/com/grab/databinding/stub/mapper/GenerateDatabindingMapperTest.kt
Header compilation is nice but that also means annotation processors are run twice per module. Databinding is already slow + consumes transitive R.txts + some databinding artifacts which affects overall parallelism. This change generates `DatabindingMapperImpl` for a module so that that public ABI of a module is fully complete (we already generate other stubs).
This way by setting `generates_api` to `False` in `java_plugin`, we can avoid running `ProcessDatabinding` twice.
This change generates a dummy `DatabindingMapperImpl` and puts it on the compile classpath alone to let header compilation succeed. There is overhead in compiling `DatabindingMapperImpl`, yes but that is worth it since it is lot less work compared to what databinding would do. 
Seeing 15% improvement in a small project …
=> Generate stub for `DatabindingMapperImpl` to completely disable databinding annotation processor in header compilation

BUILD.bazel, README.md, WORKSPACE, android/initialize.bzl, android/repositories.bzl, tools/android-mock/BUILD.bazel, tools/auto-service/BUILD.bazel, tools/binding-adapter-bridge/BUILD.bazel, tools/db-compiler-lite/BUILD, tools/test-suite-generator/BUILD.bazel, tools/test-suite/BUILD.bazel, tools/test/android/BUILD.bazel, tools/worker/BUILD.bazel, workspace_defs.bzl
Fixes #28
Bazel common tooling targets now use `bazel_common_maven` and targets that need to be present in the consumer runtime alone are added via `GRAB_BAZEL_COMMON_ARTIFACTS`. After this change, tooling updates in bazel common should not affect app runtime behavior which was the case before. Versions specified in `GRAB_BAZEL_COMMON_ARTIFACTS` can also be overriden by consuming project's versions as expected.
This also changes how bazel common is imported into consuming project via new WORKSPACE macros. Same changes are required on Grazel which will follow.
=> Refactor dependencies and split tooling and runtime classpath via separate `maven_install`

tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/parser/RTxtParser.kt
It isn't part of the spec, but this type is used in androidx.navigation. Without this, modules using androidx.navigation won't build.
(Feel free to reject if you aren't interested in supporting this as a use case; it's easy enough to keep as a fork.)
=> Add R type for navigation

src/main/starlark/test/instrumentation.bzl
The generate manifest xml for instrumentation test uses a name and output that does not allow multiple `android_instrumentation_binary` to be used. This PR address it and allows multiple `android_instrumentation_binary` to be declared with different names
=> Fix instrumentation manifest name

tools/databinding/databinding.bzl
Without this, settings `tags = ["manual"]` on a `kt_db_android_library`, for instance, still forces R classes, mapper, etc, to be built.
=> Pass tags down to child rules in `kt_db_android_library`

tools/build_config/BUILD, tools/build_config/build_config.bzl, tools/build_config/src/main/java/com/grab/buildconfig/BUILD.bazel, tools/build_config/src/main/java/com/grab/buildconfig/BuildConfigGenerator.kt, tools/build_config/src/main/java/com/grab/buildconfig/GeneratorCommand.kt, tools/build_config/src/main/java/com/grab/buildconfig/main.kt, tools/build_config/src/test/java/com/grab/buildconfig/BuildConfigTest.kt
Moving the generation of BuildConfig to analysis phase so that it is able to support [configurable build attributes](https://bazel.build/docs/configurable-attributes) (`select()`).
The BuildConfig is now generated via a java tool that is executed via genrule in order to make use of genrule's cmd to expand given `select()` in dict values
Sample of `build_config` with `select()`:
```bazel
build_config(
name = "foo-build-config",
package_name = "foo.bar",
booleans = {
"SOME_BOOLEAN": "false",
},
ints = {
"SOME_INT": 0,
"VERSION_CODE": 1,
},
longs = {
"SOME_LONG": 0,
},
strings = {
"SOME_STRING": "Something",
"VERSION_NAME": "1.0",
"TESTING": select({
"//foo:bar": ["select me"],
"//conditions:default": ["default selected"],
}),
"THIS": "THAT",
"FOO": "BAR",
},
)
```
This generates a …
=> Implement build config generation with a dedicated tool and add worker support

tools/aapt_lite/src/main/java/com/grab/aapt/AaptLiteCommand.kt, tools/aapt_lite/src/main/java/com/grab/aapt/BUILD.bazel, tools/aapt_lite/src/main/java/com/grab/aapt/databinding/util/WorkingDirectory.kt
Use a temp directory during worker execution and clean it up during exit. This is needed to ensure worker state for multiple targets and repetitive builds are consitent. This would not be needed if sanboxing or worker 
sandboxing is enabled.
=> Use temp directory and clean it up during worker execution

project_views/default.bazelproject, rules/android/android_binary.bzl, rules/android/android_library.bzl, rules/android/databinding/databinding.bzl, rules/android/resources.bzl, rules/defs.bzl
Currently we have several functionalities written as separate macros or rules like `build_config`, `res_value`, `kt_db_android_library` etc. While that works the build statements are quite verbose and are not as readable. For [example](https://github.com/grab/Grazel/blob/8edb75103e5a8b61e00d6fa493915c008b15fd32/sample-android/BUILD.bazel#L51-L177).
This PR aims to offer a unified macro for `android_library` and `android_binary`, which consolidates all functionality (kotlin, databinding, resValues and buildConfig) in a transparent manner. Bazel's macros are inexpensive, so there is no concern regarding build script evaluation performance. Additionally, using a unified macro means there are fewer concepts to teach when maintaining build scripts, and it reduces the workload for Grazel to …
=> Introduce unified `android_library` and `android_binary` macros

rules/android/private/resource_merger.bzl, tools/aapt_lite/src/main/java/com/google/devtools/build/android/OutputFixer.kt, tools/aapt_lite/src/test/java/com/google/devtools/build/android/OutputFixerTest.kt
- Handle cases where source resources already contain qualifiers like `values-v21`
- Enable workers support for `MergeSourceSet`
=> Don't remove qualifiers after resource merging if passed output files already contain it and enable workers

tools/worker/src/main/kotlin/io/bazel/streams/Streams.kt, tools/worker/src/main/kotlin/io/bazel/streams/WorkerStreams.kt
Redirect system streams in workers to ensure nothing abrupt to the worker's streams.
=> redirect system streams in workers

rules/android/android_binary.bzl, rules/android/android_library.bzl, rules/kotlin/kotlin.bzl
=> Update `lint_options.config` tag

rules/android/android_instrumentation.bzl
#102 Added compose support for `android_library` and `android_binary` but have seem to missed out adding support for `android_instrumentation_binary`. 
This PR will allow the compose compiler to be added to Kotlin compilation in `android_instrumentation_binary` when `enable_compose` is set to `True`.
=> Add compose support to android_instrumentation_binary

rules/android/android_binary.bzl, rules/android/android_library.bzl, rules/android/lint/lint_aspect.bzl, rules/android/lint/lint_sources.bzl, rules/android/lint/providers.bzl, rules/kotlin/kotlin.bzl, tools/lint/src/main/java/com/grab/lint/LintReportCommand.kt, tools/lint/src/main/java/com/grab/lint/LintResults.kt, tools/lint/src/test/java/com/grab/lint/LintResultsTest.kt
adding control over the lint exit code for warning and information issues
after this, we can control if we want to skip the Lint issues with the severity of Warning or Information or fail the task,
also, we will skip the Lint internal Issues 
```
lint_options = {
"enabled": True,
"config": "lint.xml",
"baseline": "lint_baseline.xml",
"fail_on_warning": False,
"fail_on_information": False,
},
```
=> adding control over lint exit code for warning and information issues

rules/android/lint/defs.bzl, rules/android/lint/lint_aspect.bzl, rules/android/lint/lint_inspect.bzl, rules/android/lint/providers.bzl, rules/android/utils.bzl, tools/lint/BUILD.bazel, tools/lint/src/main/java/com/grab/lint/inspector/ArgumentParser.kt, tools/lint/src/main/java/com/grab/lint/inspector/BUILD.bazel, tools/lint/src/main/java/com/grab/lint/inspector/Inspector.kt, tools/lint/src/main/java/com/grab/lint/inspector/LintIssueModel.kt, tools/lint/src/main/java/com/grab/lint/inspector/Main.kt
This utility tool helps you inspect which lint rules are applied to each target. Since lint rules can be indirectly applied to targets through AAR dependencies, it's beneficial to know exactly which rules are in effect for each target. This tool generates a JSON file that lists all the rules, provides detailed information about them, and indicates their source.
`bazelisk run target_name.lint_inspector `
=> add lint custom rule inspector

tools/custom_res/custom_res.bzl
Currently, custom_res rule enforces that dir_name is not in the same directory as the package. It does this implicitly:
```
old_resource_path.replace("/" + dir_name, "/res")
```
This means that if `"/" + dir_name` does not exist in the resource path, nothing will be replaced, and the rule fails. Meaning that, for instance:
```
.
├── BUILD.bazel
├── res
├── res-debug
└── res-release
```
This fails, because the resource path is `res-debug/values/example.xml`.
By the nature of the rule, the resource paths having dir_name plus a slash at the end feels more correct to enforce than starting with a slash.
=> Remove restriction in custom_res against top-level directory

rules/android/android_binary.bzl, rules/android/android_library.bzl, rules/check/detekt/defs.bzl, rules/defs.bzl, rules/kotlin/kotlin.bzl, rules/repositories.bzl, rules/setup.bzl, tests/android/library/BUILD.bazel, tests/android/library/detekt_baseline.xml, tests/android/library/src/main/java/com/grab/test/LibraryActivity.kt
adapting detekt 
To run Detekt checks on the target and produce the result XML, Run 
`bazelisk test <name>.detekt_test `
To update the baseline, Run 
`baselisk run <name>.detekt_update_baseline `
=> Integrate `bazel_rules_detekt` 

README.md
The README currently specifies old paths which doesn't work with the latest stable release (0.4.0).
=> Update README.md with correct paths for Grab Bazel common rules

tools/worker/BUILD.bazel
There are no .java files in this tree, so it can be removed.
=> Fix error reproduced by adding `--incompatible_disallow_empty_glob`

rules/android/compose/BUILD.bazel
Enable Jetpack Compose Strong skipping mode.
We need to update the ID because, behind the scenes, kt_compiler_plugin will pass the parameter in this format
`-P plugin:<plugin_id>:<key>=<value>`
=> Enable Jetpack Compose Strong Skipping Mode
